DROP TABLE IF EXISTS parameters CASCADE;
DROP TABLE IF EXISTS modelparameters CASCADE;
DROP TABLE IF EXISTS mode CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS accountparameters CASCADE;