DROP TABLE IF EXISTS accountparameters CASCADE;
DROP TABLE IF EXISTS modeparameters CASCADE;
DROP TABLE IF EXISTS parameters CASCADE;
DROP TABLE IF EXISTS mode CASCADE;
DROP TABLE IF EXISTS account CASCADE;
